/* GENERADO por tools/genera_plantas.mjs — NO editar a mano.
   Se rellena lat/lon EN LA CARTERA (proyectos/cartera-tabla.html) y se regenera. */
(function (raiz) {
  var CARTERA = {
   "_que_es": "Cartera de proyectos con coordenadas. GENERADO por tools/genera_plantas.mjs desde proyectos/cartera-tabla.html (SEED) y los *_layout.json de cobertura-zigbee. NO editar a mano: se rellena lat/lon EN LA CARTERA y se regenera.",
   "_fuentes": {
    "cartera": "factiun-cartera (Supabase) · exportación ⬇ CSV en datos/cartera_20260909.csv",
    "rotulos": "proyectos/cartera-tabla.html · const NPROY (equivalencia de números)",
    "emparejado": "cobertura-zigbee/plantas_indice.json · código de cartera y huso por layout",
    "layouts": "cobertura-zigbee/<planta>_layout.json · clat/clon (centroide real)"
   },
   "n_total": 32,
   "n_con_coordenadas": 30,
   "n_sin_coordenadas": 2,
   "n_homonimos": 2,
   "n_fuera_de_cartera": 1,
   "plantas": [
    {
     "num": "23003",
     "num_cartera": "24002",
     "proyecto": "El Burgo I",
     "emplazamiento": "Zaragoza",
     "provincia": "Zaragoza",
     "pais": "España",
     "estado_pem": "En marcha",
     "alim_tcu": "String",
     "bateria_tcu": "6Ah",
     "trk_total": 215,
     "lat": 41.57634197288531,
     "lon": -0.7981388191435679,
     "fuente": "layout:elburgo",
     "en_cartera": true,
     "tz": 1,
     "dst": true,
     "homonimo_de": null
    },
    {
     "num": "24007",
     "num_cartera": "24007",
     "proyecto": "Fayón",
     "emplazamiento": "Fayón",
     "provincia": "Zaragoza",
     "pais": "España",
     "estado_pem": "En marcha",
     "alim_tcu": "Selfpowered",
     "bateria_tcu": "6Ah",
     "trk_total": 24,
     "lat": 41.2269358,
     "lon": 0.3241528,
     "fuente": "layout:fayon",
     "en_cartera": true,
     "tz": 1,
     "dst": true,
     "homonimo_de": null
    },
    {
     "num": "24019",
     "num_cartera": "24019",
     "proyecto": "San José",
     "emplazamiento": "La Joya",
     "provincia": "Arequipa",
     "pais": "Perú",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "Selfpowered",
     "bateria_tcu": "6Ah",
     "trk_total": 2289,
     "lat": -16.5957735,
     "lon": -71.8064406,
     "fuente": "layout:sanjose",
     "en_cartera": true,
     "tz": -5,
     "dst": false,
     "homonimo_de": null
    },
    {
     "num": "24021",
     "num_cartera": "24021",
     "proyecto": "Túnez",
     "emplazamiento": "El Hamma",
     "provincia": "Gabes",
     "pais": "Túnez",
     "estado_pem": "En marcha",
     "alim_tcu": "Selfpowered",
     "bateria_tcu": "6Ah",
     "trk_total": 19,
     "lat": 33.879238,
     "lon": 9.8736462,
     "fuente": "layout:tunez",
     "en_cartera": true,
     "tz": 1,
     "dst": false,
     "homonimo_de": [
      "26322"
     ]
    },
    {
     "num": "24024",
     "num_cartera": "24024",
     "proyecto": "Alconadre · Sodeto",
     "emplazamiento": "Lalueza",
     "provincia": "Huesca",
     "pais": "España",
     "estado_pem": "En marcha",
     "alim_tcu": null,
     "bateria_tcu": null,
     "trk_total": 5,
     "lat": 41.926278,
     "lon": -0.277708,
     "fuente": "cartera",
     "en_cartera": true,
     "tz": 1,
     "dst": true,
     "homonimo_de": null
    },
    {
     "num": "24024",
     "num_cartera": "24024",
     "proyecto": "Alconadre · San Miguel",
     "emplazamiento": "Sena",
     "provincia": "Huesca",
     "pais": "España",
     "estado_pem": "En marcha",
     "alim_tcu": null,
     "bateria_tcu": null,
     "trk_total": 32,
     "lat": 41.607279,
     "lon": -0.140755,
     "fuente": "cartera",
     "en_cartera": true,
     "tz": 1,
     "dst": true,
     "homonimo_de": null
    },
    {
     "num": "24024",
     "num_cartera": "24024",
     "proyecto": "Alconadre · Peralta de Alcofea",
     "emplazamiento": "Peralta de Alcofea",
     "provincia": "Huesca",
     "pais": "España",
     "estado_pem": "En marcha",
     "alim_tcu": null,
     "bateria_tcu": null,
     "trk_total": 22,
     "lat": 41.946462,
     "lon": -0.075749,
     "fuente": "cartera",
     "en_cartera": true,
     "tz": 1,
     "dst": true,
     "homonimo_de": null
    },
    {
     "num": "24025",
     "num_cartera": "24025",
     "proyecto": "Ayora",
     "emplazamiento": "Jarafuel",
     "provincia": "Valencia",
     "pais": "España",
     "estado_pem": "En marcha",
     "alim_tcu": "String",
     "bateria_tcu": "6Ah",
     "trk_total": 754,
     "lat": 39.1182081,
     "lon": -1.1598527,
     "fuente": "layout:ayora",
     "en_cartera": true,
     "tz": 1,
     "dst": true,
     "homonimo_de": null
    },
    {
     "num": "24029",
     "num_cartera": "24029",
     "proyecto": "La Latina 2",
     "emplazamiento": "Borgo Piave",
     "provincia": "Latina",
     "pais": "Italia",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "String",
     "bateria_tcu": "6Ah",
     "trk_total": 67,
     "lat": 41.450808,
     "lon": 12.816564,
     "fuente": "cartera",
     "en_cartera": true,
     "tz": 1,
     "dst": true,
     "homonimo_de": null
    },
    {
     "num": "24030",
     "num_cartera": "24030",
     "proyecto": "Bagnarelli",
     "emplazamiento": "Lucera",
     "provincia": "Foggia",
     "pais": "Italia",
     "estado_pem": "En marcha",
     "alim_tcu": "String",
     "bateria_tcu": "6Ah",
     "trk_total": 17,
     "lat": 41.5156065,
     "lon": 15.2676234,
     "fuente": "layout:bagnarelli",
     "en_cartera": true,
     "tz": 1,
     "dst": true,
     "homonimo_de": null
    },
    {
     "num": "25004",
     "num_cartera": "25004",
     "proyecto": "Benante",
     "emplazamiento": "Lentini",
     "provincia": "Siracusa (SR)-Catania (CT)",
     "pais": "Italia",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "Selfpowered",
     "bateria_tcu": "6Ah",
     "trk_total": 653,
     "lat": 37.3755148,
     "lon": 14.9043744,
     "fuente": "layout:benante",
     "en_cartera": true,
     "tz": 1,
     "dst": true,
     "homonimo_de": null
    },
    {
     "num": "25004.2",
     "num_cartera": "25004.2",
     "proyecto": "Panbianco",
     "emplazamiento": "Lentini",
     "provincia": "Siracusa (SR)-Catania (CT)",
     "pais": "Italia",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "Selfpowered",
     "bateria_tcu": "6Ah",
     "trk_total": 1311,
     "lat": 37.3710751,
     "lon": 14.8910762,
     "fuente": "layout:panbianco",
     "en_cartera": true,
     "tz": 1,
     "dst": true,
     "homonimo_de": null
    },
    {
     "num": "25019",
     "num_cartera": "25019",
     "proyecto": "Paramo",
     "emplazamiento": "Villamañán",
     "provincia": "León",
     "pais": "España",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "Selfpowered",
     "bateria_tcu": "6Ah",
     "trk_total": 396,
     "lat": 42.3205897,
     "lon": -5.5998076,
     "fuente": "layout:paramo",
     "en_cartera": true,
     "tz": 1,
     "dst": true,
     "homonimo_de": null
    },
    {
     "num": "25032",
     "num_cartera": "25032",
     "proyecto": "Trani",
     "emplazamiento": "Barletta",
     "provincia": "Apulia",
     "pais": "Italia",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "String",
     "bateria_tcu": "6Ah",
     "trk_total": 19,
     "lat": 41.253973,
     "lon": 16.350812,
     "fuente": "cartera",
     "en_cartera": true,
     "tz": 1,
     "dst": true,
     "homonimo_de": null
    },
    {
     "num": "25082",
     "num_cartera": "25082",
     "proyecto": "El polvorin + Higueras",
     "emplazamiento": "Polvorin + Higueras",
     "provincia": "Badajoz",
     "pais": "España",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "Selfpowered",
     "bateria_tcu": "6Ah",
     "trk_total": 119,
     "lat": 38.8411992,
     "lon": -6.9996917,
     "fuente": "layout:polvorin",
     "en_cartera": true,
     "tz": 1,
     "dst": true,
     "homonimo_de": null
    },
    {
     "num": "25120",
     "num_cartera": "25120",
     "proyecto": "Monteodorisio",
     "emplazamiento": "Monteodorisio",
     "provincia": "Chieti",
     "pais": "Italia",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "String",
     "bateria_tcu": "6Ah",
     "trk_total": 30,
     "lat": 42.076444,
     "lon": 14.602333,
     "fuente": "cartera",
     "en_cartera": true,
     "tz": 1,
     "dst": true,
     "homonimo_de": null
    },
    {
     "num": "25131",
     "num_cartera": "25131",
     "proyecto": "Galatina",
     "emplazamiento": "Galatina",
     "provincia": "Lecce",
     "pais": "Italia",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "String",
     "bateria_tcu": "6Ah",
     "trk_total": 18,
     "lat": 40.190222,
     "lon": 18.160139,
     "fuente": "cartera",
     "en_cartera": true,
     "tz": 1,
     "dst": true,
     "homonimo_de": null
    },
    {
     "num": "25200",
     "num_cartera": "25200",
     "proyecto": "Ercolino",
     "emplazamiento": "Ercolino",
     "provincia": "Pescara",
     "pais": "Italia",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "Agri Selfpowered",
     "bateria_tcu": "6Ah",
     "trk_total": 128,
     "lat": 42.502556,
     "lon": 14.090556,
     "fuente": "cartera",
     "en_cartera": true,
     "tz": 1,
     "dst": true,
     "homonimo_de": null
    },
    {
     "num": "26009",
     "num_cartera": "26009",
     "proyecto": "Valle de Moinhos",
     "emplazamiento": "Cartaxo",
     "provincia": "Santarem",
     "pais": "Portugal",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "Selfpowered",
     "bateria_tcu": "6Ah",
     "trk_total": 64,
     "lat": 39.210367,
     "lon": -8.774147,
     "fuente": "cartera",
     "en_cartera": true,
     "tz": 0,
     "dst": true,
     "homonimo_de": null
    },
    {
     "num": "26057",
     "num_cartera": "26057",
     "proyecto": "Minervino",
     "emplazamiento": null,
     "provincia": null,
     "pais": "Italia",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "String",
     "bateria_tcu": null,
     "trk_total": 39,
     "lat": null,
     "lon": null,
     "fuente": null,
     "en_cartera": true,
     "tz": 1,
     "dst": true,
     "homonimo_de": null
    },
    {
     "num": "26078",
     "num_cartera": "26078",
     "proyecto": "Monsano",
     "emplazamiento": null,
     "provincia": null,
     "pais": "Italia",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "Selfpowered",
     "bateria_tcu": "6Ah",
     "trk_total": 87,
     "lat": null,
     "lon": null,
     "fuente": null,
     "en_cartera": true,
     "tz": 1,
     "dst": true,
     "homonimo_de": null
    },
    {
     "num": "26094",
     "num_cartera": "26094",
     "proyecto": "Conselice",
     "emplazamiento": null,
     "provincia": null,
     "pais": "Italia",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "String",
     "bateria_tcu": "6Ah",
     "trk_total": 32,
     "lat": 44.570162,
     "lon": 11.877814,
     "fuente": "cartera",
     "en_cartera": true,
     "tz": 1,
     "dst": true,
     "homonimo_de": null
    },
    {
     "num": "26102",
     "num_cartera": "26102",
     "proyecto": "Jabalí",
     "emplazamiento": "Cáceres",
     "provincia": "Cáceres",
     "pais": "España",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "Selfpowered",
     "bateria_tcu": "6Ah",
     "trk_total": 104,
     "lat": 39.463306,
     "lon": -6.297472,
     "fuente": "cartera",
     "en_cartera": true,
     "tz": 1,
     "dst": true,
     "homonimo_de": null
    },
    {
     "num": "26103",
     "num_cartera": "26103",
     "proyecto": "Piñuelas",
     "emplazamiento": "Cáceres",
     "provincia": "Cáceres",
     "pais": "España",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "Selfpowered",
     "bateria_tcu": "6Ah",
     "trk_total": 93,
     "lat": 39.460833,
     "lon": -6.289833,
     "fuente": "cartera",
     "en_cartera": true,
     "tz": 1,
     "dst": true,
     "homonimo_de": null
    },
    {
     "num": "26126.1",
     "num_cartera": "26126.1",
     "proyecto": "Tolocha I",
     "emplazamiento": "Híjar",
     "provincia": "Teruel",
     "pais": "España",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "Selfpowered",
     "bateria_tcu": "6Ah",
     "trk_total": 775,
     "lat": 41.041856,
     "lon": -0.454403,
     "fuente": "cartera",
     "en_cartera": true,
     "tz": 1,
     "dst": true,
     "homonimo_de": null
    },
    {
     "num": "26126.2",
     "num_cartera": "26126.2",
     "proyecto": "Sedeis VI",
     "emplazamiento": "Híjar",
     "provincia": "Teruel",
     "pais": "España",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "Selfpowered",
     "bateria_tcu": "6Ah",
     "trk_total": 754,
     "lat": 41.047686,
     "lon": -0.442306,
     "fuente": "cartera",
     "en_cartera": true,
     "tz": 1,
     "dst": true,
     "homonimo_de": null
    },
    {
     "num": "26126.3",
     "num_cartera": "26126.3",
     "proyecto": "Ilio III",
     "emplazamiento": "Híjar",
     "provincia": "Teruel",
     "pais": "España",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "Selfpowered",
     "bateria_tcu": "6Ah",
     "trk_total": 567,
     "lat": 41.034787,
     "lon": -0.455362,
     "fuente": "cartera",
     "en_cartera": true,
     "tz": 1,
     "dst": true,
     "homonimo_de": null
    },
    {
     "num": "26246",
     "num_cartera": "26246",
     "proyecto": "Agraval",
     "emplazamiento": null,
     "provincia": null,
     "pais": "India",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "String",
     "bateria_tcu": "4,5Ah",
     "trk_total": 18,
     "lat": 21.521096,
     "lon": 72.124651,
     "fuente": "cartera",
     "en_cartera": true,
     "tz": 5.5,
     "dst": false,
     "homonimo_de": null
    },
    {
     "num": "26322",
     "num_cartera": "26322",
     "proyecto": "Túnez",
     "emplazamiento": "El Hamma",
     "provincia": "Gabes",
     "pais": "Túnez",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "Selfpowered",
     "bateria_tcu": "6Ah",
     "trk_total": 3,
     "lat": 33.87878,
     "lon": 9.87395,
     "fuente": "cartera",
     "en_cartera": true,
     "tz": 1,
     "dst": false,
     "homonimo_de": [
      "24021"
     ]
    },
    {
     "num": "26361",
     "num_cartera": "26361",
     "proyecto": "SAP Belcastro",
     "emplazamiento": null,
     "provincia": null,
     "pais": "Italia",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "Selfpowered",
     "bateria_tcu": "6Ah",
     "trk_total": 79,
     "lat": 38.945831,
     "lon": 16.898029,
     "fuente": "cartera",
     "en_cartera": true,
     "tz": 1,
     "dst": true,
     "homonimo_de": null
    },
    {
     "num": "26411",
     "num_cartera": "26411",
     "proyecto": "Tuva",
     "emplazamiento": null,
     "provincia": null,
     "pais": "India",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "String",
     "bateria_tcu": "4,5Ah",
     "trk_total": 40,
     "lat": 22.593027,
     "lon": 71.601735,
     "fuente": "cartera",
     "en_cartera": true,
     "tz": 5.5,
     "dst": false,
     "homonimo_de": null
    },
    {
     "num": null,
     "num_cartera": null,
     "proyecto": "El Naranjo Dicayagua",
     "emplazamiento": null,
     "provincia": null,
     "pais": null,
     "estado_pem": "oferta",
     "alim_tcu": null,
     "bateria_tcu": null,
     "trk_total": 5493,
     "lat": 19.4229387,
     "lon": -70.7723283,
     "fuente": "layout:dicayagua",
     "tz": -4,
     "dst": false,
     "homonimo_de": null,
     "en_cartera": false,
     "nota": "no figura en el SEED de la cartera; si se da de alta, ponerle aquí su número"
    }
   ]
  };

  /* Rótulo canónico de una planta. Lo consumen index.html y bateria.html; no se
     escribe a mano en ninguna de las dos. */
  CARTERA.PAIS_ISO = {'España':'ES','Italia':'IT','Portugal':'PT','Perú':'PE','Túnez':'TN'};
  CARTERA.rotulo = function (p) {
    var partes = [], vistos = {};
    /* «Zaragoza, Zaragoza» no, y tampoco «El polvorin + Higueras (El polvorin +
       Higueras)»: se descarta lo que ya dice el nombre del proyecto. */
    var proy = (p.proyecto || '').toLowerCase();
    [p.emplazamiento, p.provincia].forEach(function (x) {
      if (!x || vistos[x]) return;
      if (proy.indexOf(x.toLowerCase()) >= 0) return;
      vistos[x] = 1; partes.push(x);
    });
    var iso = CARTERA.PAIS_ISO[p.pais] || p.pais || '';
    var donde = partes.concat(iso ? [iso] : []).join(', ');
    /* Dos proyectos con el mismo nombre son dos PLANTAS: la cartera tiene dos
       «Túnez», el 24021 y el 26322. Se dice en el rótulo para que nadie los lea
       como duplicado y simule uno creyendo que es el otro. */
    var aviso = p.homonimo_de && p.homonimo_de.length
              ? ' — otro proyecto, no es el ' + p.homonimo_de.join(' ni el ') : '';
    /* Las que tienen layout pero no ficha en la cartera no llevan número, y se
       dice por qué: si no, parecen un proyecto al que se le ha perdido el suyo. */
    if (p.en_cartera === false) {
      return p.proyecto + (donde ? ' (' + donde + ')' : '')
           + ' — con layout, sin ficha en la cartera'
           + (p.estado_pem ? ' (' + p.estado_pem + ')' : '');
    }
    return p.num + ' · ' + p.proyecto + (donde ? ' (' + donde + ')' : '') + aviso;
  };
  if (typeof window !== "undefined") window.CARTERA = CARTERA;
  if (typeof module !== "undefined") module.exports = CARTERA;
})(this);
