/* GENERADO por tools/genera_plantas.mjs — NO editar a mano.
   Se rellena lat/lon EN LA CARTERA (proyectos/cartera-tabla.html) y se regenera. */
(function (raiz) {
  var CARTERA = {
   "_que_es": "Cartera de proyectos con coordenadas. GENERADO por tools/genera_plantas.mjs desde proyectos/cartera-tabla.html (SEED) y los *_layout.json de cobertura-zigbee. NO editar a mano: se rellena lat/lon EN LA CARTERA y se regenera.",
   "_fuentes": {
    "cartera": "proyectos/cartera-tabla.html · const SEED",
    "layouts": "cobertura-zigbee/<planta>_layout.json · clat/clon (centroide real)"
   },
   "n_total": 22,
   "n_con_coordenadas": 10,
   "n_sin_coordenadas": 12,
   "n_homonimos": 2,
   "plantas": [
    {
     "num": "23003",
     "num_cartera": "24002",
     "proyecto": "El Burgo I",
     "emplazamiento": "Zaragoza",
     "provincia": "Zaragoza",
     "pais": "España",
     "estado_pem": "En marcha",
     "alim_tcu": "Stringpowered",
     "bateria_tcu": "6Ah",
     "trk_total": 215,
     "lat": 41.57634197288531,
     "lon": -0.7981388191435679,
     "fuente": "layout:elburgo",
     "homonimo_de": null
    },
    {
     "num": "24007",
     "num_cartera": "24007",
     "proyecto": "Fayón",
     "emplazamiento": "Fayón",
     "provincia": "Zaragoza",
     "pais": "España",
     "estado_pem": "En marcha",
     "alim_tcu": "Selfpowered",
     "bateria_tcu": "6Ah",
     "trk_total": 24,
     "lat": 41.2269358,
     "lon": 0.3241528,
     "fuente": "layout:fayon",
     "homonimo_de": null
    },
    {
     "num": "24019",
     "num_cartera": "24019",
     "proyecto": "San José",
     "emplazamiento": "La Joya",
     "provincia": "Arequipa",
     "pais": "Perú",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "Selfpowered",
     "bateria_tcu": "6Ah",
     "trk_total": 2289,
     "lat": -16.5957735,
     "lon": -71.8064406,
     "fuente": "layout:sanjose",
     "homonimo_de": null
    },
    {
     "num": "24021",
     "num_cartera": "24021",
     "proyecto": "Túnez",
     "emplazamiento": "El Hamma",
     "provincia": "Gabes",
     "pais": "Túnez",
     "estado_pem": "En marcha",
     "alim_tcu": "Selfpowered",
     "bateria_tcu": "6Ah",
     "trk_total": 19,
     "lat": 33.879238,
     "lon": 9.8736462,
     "fuente": "layout:tunez",
     "homonimo_de": [
      "26322"
     ]
    },
    {
     "num": "24025",
     "num_cartera": "24025",
     "proyecto": "Ayora",
     "emplazamiento": "Jarafuel",
     "provincia": "Valencia",
     "pais": "España",
     "estado_pem": "En proceso",
     "alim_tcu": "Stringpowered",
     "bateria_tcu": "6Ah",
     "trk_total": 754,
     "lat": 39.1182081,
     "lon": -1.1598527,
     "fuente": "layout:ayora",
     "homonimo_de": null
    },
    {
     "num": "25032",
     "num_cartera": "25032",
     "proyecto": "Trani",
     "emplazamiento": "Barletta",
     "provincia": "Apulia",
     "pais": "Italia",
     "estado_pem": "Sin comenzar",
     "alim_tcu": null,
     "bateria_tcu": null,
     "trk_total": 19,
     "lat": null,
     "lon": null,
     "fuente": null,
     "homonimo_de": null
    },
    {
     "num": "24030",
     "num_cartera": "24030",
     "proyecto": "Bagnarelli",
     "emplazamiento": "Lucera",
     "provincia": "Foggia",
     "pais": "Italia",
     "estado_pem": "En marcha",
     "alim_tcu": "Stringpowered",
     "bateria_tcu": "6Ah",
     "trk_total": 17,
     "lat": 41.5156065,
     "lon": 15.2676234,
     "fuente": "layout:bagnarelli",
     "homonimo_de": null
    },
    {
     "num": "25019",
     "num_cartera": "25019",
     "proyecto": "Paramo",
     "emplazamiento": "Villamañán",
     "provincia": "León",
     "pais": "España",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "Selfpowered",
     "bateria_tcu": "6Ah",
     "trk_total": 396,
     "lat": 42.3205897,
     "lon": -5.5998076,
     "fuente": "layout:paramo",
     "homonimo_de": null
    },
    {
     "num": "25082",
     "num_cartera": "25082",
     "proyecto": "El polvorin + Higueras",
     "emplazamiento": "Polvorin + Higueras",
     "provincia": "Badajoz",
     "pais": "España",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "Selfpowered",
     "bateria_tcu": "6Ah",
     "trk_total": 119,
     "lat": 38.8411992,
     "lon": -6.9996917,
     "fuente": "layout:polvorin",
     "homonimo_de": null
    },
    {
     "num": "25120",
     "num_cartera": "25120",
     "proyecto": "Monteodorisio",
     "emplazamiento": "Monteodorisio",
     "provincia": "Chieti",
     "pais": "Italia",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "Stringpowered",
     "bateria_tcu": "6Ah",
     "trk_total": 30,
     "lat": null,
     "lon": null,
     "fuente": null,
     "homonimo_de": null
    },
    {
     "num": "25131",
     "num_cartera": "25131",
     "proyecto": "Galatina",
     "emplazamiento": "Galatina",
     "provincia": "Lecce",
     "pais": "Italia",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "Stringpowered",
     "bateria_tcu": "6Ah",
     "trk_total": 18,
     "lat": null,
     "lon": null,
     "fuente": null,
     "homonimo_de": null
    },
    {
     "num": "25200",
     "num_cartera": "25200",
     "proyecto": "Ercolino",
     "emplazamiento": "Ercolino",
     "provincia": "Pescara",
     "pais": "Italia",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "Agri Selfpowered",
     "bateria_tcu": "6Ah",
     "trk_total": 128,
     "lat": null,
     "lon": null,
     "fuente": null,
     "homonimo_de": null
    },
    {
     "num": "26102",
     "num_cartera": "26102",
     "proyecto": "Jabalí",
     "emplazamiento": "Cáceres",
     "provincia": "Cáceres",
     "pais": "España",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "Selfpowered",
     "bateria_tcu": "6Ah",
     "trk_total": 104,
     "lat": null,
     "lon": null,
     "fuente": null,
     "homonimo_de": null
    },
    {
     "num": "26103",
     "num_cartera": "26103",
     "proyecto": "Piñuelas",
     "emplazamiento": "Cáceres",
     "provincia": "Cáceres",
     "pais": "España",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "Selfpowered",
     "bateria_tcu": "6Ah",
     "trk_total": 93,
     "lat": null,
     "lon": null,
     "fuente": null,
     "homonimo_de": null
    },
    {
     "num": "25004",
     "num_cartera": "25004",
     "proyecto": "Benante",
     "emplazamiento": null,
     "provincia": null,
     "pais": "Italia",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "Selfpowered",
     "bateria_tcu": "6Ah",
     "trk_total": null,
     "lat": 37.3755148,
     "lon": 14.9043744,
     "fuente": "layout:benante",
     "homonimo_de": null
    },
    {
     "num": "25004.2",
     "num_cartera": "25004.2",
     "proyecto": "Panbianco",
     "emplazamiento": null,
     "provincia": null,
     "pais": "Italia",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "Selfpowered",
     "bateria_tcu": "6Ah",
     "trk_total": null,
     "lat": 37.3710751,
     "lon": 14.8910762,
     "fuente": "layout:panbianco",
     "homonimo_de": null
    },
    {
     "num": "26009",
     "num_cartera": "26009",
     "proyecto": "Valle de Moinhos",
     "emplazamiento": null,
     "provincia": null,
     "pais": "Portugal",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "Selfpowered",
     "bateria_tcu": "6Ah",
     "trk_total": null,
     "lat": null,
     "lon": null,
     "fuente": null,
     "homonimo_de": null
    },
    {
     "num": "24029",
     "num_cartera": "24029",
     "proyecto": "La Latina 2",
     "emplazamiento": null,
     "provincia": null,
     "pais": "Italia",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "Stringpowered",
     "bateria_tcu": "6Ah",
     "trk_total": null,
     "lat": null,
     "lon": null,
     "fuente": null,
     "homonimo_de": null
    },
    {
     "num": "26126.1",
     "num_cartera": "26126.1",
     "proyecto": "Tolocha I",
     "emplazamiento": null,
     "provincia": null,
     "pais": "España",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "Selfpowered",
     "bateria_tcu": "6Ah",
     "trk_total": null,
     "lat": null,
     "lon": null,
     "fuente": null,
     "homonimo_de": null
    },
    {
     "num": "26126.2",
     "num_cartera": "26126.2",
     "proyecto": "Sedeis VI",
     "emplazamiento": null,
     "provincia": null,
     "pais": "España",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "Selfpowered",
     "bateria_tcu": "6Ah",
     "trk_total": null,
     "lat": null,
     "lon": null,
     "fuente": null,
     "homonimo_de": null
    },
    {
     "num": "26322",
     "num_cartera": "26322",
     "proyecto": "Túnez",
     "emplazamiento": null,
     "provincia": null,
     "pais": "Túnez",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "Selfpowered",
     "bateria_tcu": "6Ah",
     "trk_total": null,
     "lat": null,
     "lon": null,
     "fuente": null,
     "homonimo_de": [
      "24021"
     ]
    },
    {
     "num": "24024",
     "num_cartera": "24024",
     "proyecto": "Alconadre",
     "emplazamiento": null,
     "provincia": null,
     "pais": "España",
     "estado_pem": "Sin comenzar",
     "alim_tcu": "Selfpowered",
     "bateria_tcu": "6Ah",
     "trk_total": null,
     "lat": null,
     "lon": null,
     "fuente": null,
     "homonimo_de": null
    }
   ]
  };
  if (typeof window !== "undefined") window.CARTERA = CARTERA;
  if (typeof module !== "undefined") module.exports = CARTERA;
})(this);
